pragma solidity ^0.5.1;

import { IERC20 } from "openzeppelin-solidity/contracts/token/ERC20/IERC20.sol";

library CTHelpers {
    /// @dev Constructs a condition ID from an oracle, a question ID, and the outcome slot count for the question.
    /// @param oracle The account assigned to report the result for the prepared condition.
    /// @param questionId An identifier for the question to be answered by the oracle.
    /// @param outcomeSlotCount The number of outcome slots which should be used for this condition. Must not exceed 256.
    function getConditionId(address oracle, bytes32 questionId, uint outcomeSlotCount) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked(oracle, questionId, outcomeSlotCount));
    }

    uint constant P = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
    uint constant B = 3;

    function sqrt(uint yy) private pure returns (uint y) {
        uint p = P;
        assembly {
            // 1100000110010001
            y := mulmod(yy, yy, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 0011100111001011
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 1000010011000110
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            // 1000000010100110
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            // 1110000101000001
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 0001011011011010
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            // 0000011000000101
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 0110000101110110
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            // 0101111000000101
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 1010101001000101
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 1010000111000111
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 0010101000110100
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            // 1111000010000010
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            // 0011000001011011
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 0110000111110011
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            // 111101010010
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, y, p)
            y := mulmod(y, yy, p)
            y := mulmod(y, y, p)
        }
    }

    /// @dev Constructs an outcome collection ID from a parent collection and an outcome collection.
    /// @param parentCollectionId Collection ID of the parent outcome collection, or bytes32(0) if there's no parent.
    /// @param conditionId Condition ID of the outcome collection to combine with the parent outcome collection.
    /// @param indexSet Index set of the outcome collection to combine with the parent outcome collection.
    function getCollectionId(bytes32 parentCollectionId, bytes32 conditionId, uint indexSet) internal view returns (bytes32) {
        uint x1 = uint(keccak256(abi.encodePacked(conditionId, indexSet)));
        bool odd = x1 >> 255 != 0;
        uint y1;
        uint yy;
        do {
            x1 = addmod(x1, 1, P);
            yy = addmod(mulmod(x1, mulmod(x1, x1, P), P), B, P);
            y1 = sqrt(yy);
        } while(mulmod(y1, y1, P) != yy);
        if(odd && y1 % 2 == 0 || !odd && y1 % 2 == 1)
            y1 = P - y1;

        uint x2 = uint(parentCollectionId);
        if(x2 != 0) {
            odd = x2 >> 254 != 0;
            x2 = (x2 << 2) >> 2;
            yy = addmod(mulmod(x2, mulmod(x2, x2, P), P), B, P);
            uint y2 = sqrt(yy);
            if(odd && y2 % 2 == 0 || !odd && y2 % 2 == 1)
                y2 = P - y2;
            require(mulmod(y2, y2, P) == yy, "invalid parent collection ID");

            (bool success, bytes memory ret) = address(6).staticcall(abi.encode(x1, y1, x2, y2));
            require(success, "ecadd failed");
            (x1, y1) = abi.decode(ret, (uint, uint));
        }

        if(y1 % 2 == 1)
            x1 ^= 1 << 254;
        
        return bytes32(x1);
    }

    /// @dev Constructs a position ID from a collateral token and an outcome collection. These IDs are used as the ERC-1155 ID for this contract.
    /// @param collateralToken Collateral token which backs the position.
    /// @param collectionId ID of the outcome collection associated with this position.
    function getPositionId(IERC20 collateralToken, bytes32 collectionId) internal pure returns (uint) {
        return uint(keccak256(abi.encodePacked(collateralToken, collectionId)));
    }
}